language: python
dist: xenial
cache: npm

python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pygments

before_install:
  - sudo snap install hugo --channel=extended
  - nvm install 10.4.0
  - git submodule update --init --recursive
  - curl https://htmltest.wjdp.uk | bash

install:
  - rm -rf public 2> /dev/null
  - npm install

script:
  - hugo
  - npm run test:spelling
  - ./bin/htmltest
