<<<<<<< HEAD
#  Copyright © 2019 Cask Data, Inc.
=======
#  Copyright © 2018 Cask Data, Inc.
>>>>>>> 7bbe8df... Licenses and improved spell/links check
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

baseURL = ""
title = "CDAP"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["cdap"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "CDAP"
description = "The Data Analytics Platform"
about = "A 100% open source, integrated framework that accelerates application development for data analytics"
languageName ="English"
# Weight used for sorting.
weight = 1
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"


# Everything below this are Site Params

[params]
copyright = "Global Inc"
privacy_policy = "https://policies.google.com/privacy"
github_repo = "https://github.com/google/docsy-example"
logo = "/images/logo.svg"

  [params.cta]
    enable = true
    title = "Get STARTED"
  [params.learnMore]
    enable = true
    title = "Learn More"
  [params.noResults]
    title = "No results found"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).

[[languages.en.menu.main]]
identifier = "Get started"
url = "/cloud/"
name = "Get started"
weight = 10

[[languages.en.menu.main]]
identifier = "Accelerators"
url = "/accelerators/"
name = "Accelerators"
weight = 20

[[languages.en.menu.main]]
identifier = "Resources"
name = "Resources"
weight = 30

[[languages.en.menu.main]]
identifier = "Case Studies"
url = "/case-studies"
parent = "Resources"
name = "Case Studies"
weight = 10

[[languages.en.menu.main]]
identifier = "Plugins"
url = "/plugins"
parent = "Resources"
name = "Plugins"
weight = 30

[[languages.en.menu.main]]
identifier = "Videos"
url = "/accelerators/preparation/#videos"
parent = "Resources"
name = "Videos"
weight = 40

[[languages.en.menu.main]]
identifier = "Documentation"
post = "external"
url = "https://docs.cdap.io/current"
parent = "Resources"
name = "Documentation"
weight = 50

[[languages.en.menu.main]]
identifier = "Blog"
post = "external"
url = "https://cdap.io/"
parent = "Resources"
name = "Blog"
weight = 60

[[languages.en.menu.main]]
identifier = "Community"
url = "/community/"
name = "Community"
weight = 40

[[languages.en.menu.get_started]]
identifier = "Cloud"
url = "/cloud/"
name = "Cloud"

[[languages.en.menu.get_started]]
identifier = "Premises"
url = "/on-premises/"
name = "On Premises"
